# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.provider "virtualbox" do |v|
    v.name = "ansible"
    v.cpus = 1
    v.memory = 256 
  end
  config.vm.box = "centos/7"
  config.vm.hostname = "ansible.local"
  config.vm.network "forwarded_port", guest:80, host:8080
  config.vm.network :private_network, ip: "10.100.0.2"
  config.vm.provision :shell, path: "bootstrap.sh"
  config.vbguest.auto_update = false
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "playbook.yml"
  end
end
