# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "geerlingguy/centos7"
  config.ssh.insert_key = false
  config.vm.synced_folder ".", "/vagrant", disabled: true

  config.vm.provider :virtualbox do |v|
    v.memory = 256
    v.linked_clone = true
  end

  config.vm.define "app1" do |app|
    app.vm.hostname = "server-app1.local"
    app.vm.network :private_network, ip: "10.200.0.2"
  end

  config.vm.define "app2" do |app|
    app.vm.hostname = "server-app2.local"
    app.vm.network :private_network, ip: "10.200.0.3"
  end

  config.vm.define "db" do |db|
    db.vm.hostname = "server-db.local"
    db.vm.network :private_network, ip: "10.200.0.4"
  end

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "playbook.yml"
  end
end
